/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.hvl.dat250.s798264.exp1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testConvertToMeters() {
        assertEquals(0.127, App.convertToMeters("in", 5));
    }

    @Test void testMeterConvertToOtherScalars() {
        assertEquals(9.84251968503937,App.convertToOtherScalars("ft", 3));
    }

}
